### ISSUE TITLE
Configuring ActiveRecord backend as first in chain causes errors during initialization

### ISSUE THREAD

**Issue by Alex-Quinn** [svenfuchs/i18n-active_record#132]
### Issue

I'd like to configure my application such that the ActiveRecord backend takes precedence over the Simple backend like this:

```ruby
# config/initializers/i18n_active_record.rb
I18n.backend = I18n::Backend::Chain.new(::I18n::Backend::ActiveRecord.new, ::I18n::Backend::Simple.new)
```

However, with the above configuration, the `rake db:*` tasks fail because Rails relies on translations during app initialization:

https://github.com/rails/rails/blob/27a5ec76eed1e5d0bc5649b0e92097267c0b4338/railties/lib/rails/application/finisher.rb#L36

If a database connection hasn't been established by that point, the translation done by Rails fails via the ActiveRecord backend. In that case, errors like the following are raised:

```
# rake db:create
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  database "development_database" does not exist
<rails_app>/config/environment.rb:7:in `<top (required)>'
../.rbenv/versions/2.7.5/bin/bundle:23:in `load'
../.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'

Caused by:
PG::ConnectionBad: FATAL:  database "development_database" does not exist
<rails_app>/config/environment.rb:7:in `<top (required)>'
../.rbenv/versions/2.7.5/bin/bundle:23:in `load'
../.rbenv/versions/2.7.5/bin/bundle:23:in `<main>'
Tasks: TOP => db:create => db:load_config => environment
(See full trace by running task with --trace)
```

Full backtrace:

```
FATAL:  database "development_database" does not exist
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:1125:in `retrieve_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/connection_handling.rb:189:in `connection'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:517:in `load_schema!'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/attributes.rb:247:in `load_schema!'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:507:in `block in load_schema'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:504:in `synchronize'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:504:in `load_schema'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:391:in `attribute_types'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/model_schema.rb:415:in `type_for_attribute'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/table_metadata.rb:33:in `type'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:51:in `build'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:109:in `block in expand_from_hash'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:68:in `each'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:68:in `flat_map'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:68:in `expand_from_hash'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/where_clause_factory.rb:19:in `build'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/query_methods.rb:656:in `where!'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/relation/query_methods.rb:649:in `where'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activerecord-6.0.4.8/lib/active_record/querying.rb:21:in `where'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-active_record-1.1.0/lib/i18n/backend/active_record/translation.rb:62:in `locale'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-active_record-1.1.0/lib/i18n/backend/active_record.rb:91:in `lookup'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/memoize.rb:41:in `lookup'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/base.rb:33:in `translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/chain.rb:61:in `block (2 levels) in translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/chain.rb:59:in `catch'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/chain.rb:59:in `block in translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/chain.rb:58:in `each'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n/backend/chain.rb:58:in `translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n.rb:221:in `block in translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n.rb:217:in `catch'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/i18n-1.10.0/lib/i18n.rb:217:in `translate'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/activesupport-6.0.4.8/lib/active_support/core_ext/array/conversions.rb:70:in `to_sentence'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/application/finisher.rb:36:in `block in <module:Finisher>'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:32:in `instance_exec'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:32:in `run'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:61:in `block in run_initializers'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `call'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
../.rbenv/versions/2.7.5/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/initializable.rb:60:in `run_initializers'
../.rbenv/versions/2.7.5/lib/ruby/gems/2.7.0/gems/railties-6.0.4.8/lib/rails/application.rb:363:in `initialize!'
<rails_app>/config/environment.rb:8:in `<top (required)>'
```

### Proposed Fix

Generally, it seems reasonable for the ActiveRecord backend to fail a translation lookup when a database connection cannot be established rather than raising an exception. The i18n gem provides a mechanism for backends to define such failure cases by using `throw(:exception)`:

https://github.com/ruby-i18n/i18n/blob/b805537905522beb95ee7fc772fc8b6e150e1dbe/lib/i18n/backend/chain.rb#L59-L67

Perhaps, `i18n-active_record` could `throw(:exception)` when a database connection cannot be established. I'd also be fine if users of the `i18n-active_record` gem could opt-in to such behavior.

### Potential Workaround

For now, in my application I've setup my initializer to use a Simple backend during app boot. Then, after app initialization I reconfigure the i18n backend to include ActiveRecord. Something like this:

```ruby
# config/initializers/i18n_active_record.rb
I18n.backend = I18n::Backend::Chain.new(::I18n::Backend::Simple.new)
```

```ruby
# config/environment.rb
Rails.application.initialize!
I18n.backend = I18n::Backend::Chain.new(::I18n::Backend::ActiveRecord.new, ::I18n::Backend::Simple.new)
```

It's not clear to me if there is a more idiomatic way to achieve my intended outcome.

**Comment by Alex-Quinn** [comment]
Thanks for the quick response @timfjord!

I was able to implement your proposed solution and it works well. Initially I was thinking I needed to configure the AR backend in all app boot cases but, to your point, that's not necessary or feasible in all cases (e.g. `rake db:create`).

Thanks for your help! I'm going to close this issue.
